kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: svl-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.30.6
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
  - role: worker
    image: kindest/node:v1.30.6
  - role: worker
    image: kindest/node:v1.30.6
