apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: svl-webstack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SemVanderlinden/svl-gitops.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: svl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
